USE taskforce;
INSERT INTO stop_words(id, value) VALUES (1, 'и');
INSERT INTO stop_words(id, value) VALUES (2, 'или');
INSERT INTO stop_words(id, value) VALUES (3, 'в');
INSERT INTO stop_words(id, value) VALUES (4, 'на');
INSERT INTO stop_words(id, value) VALUES (5, 'у');
INSERT INTO stop_words(id, value) VALUES (6, 'при');
INSERT INTO stop_words(id, value) VALUES (7, 'с');
INSERT INTO stop_words(id, value) VALUES (8, 'над');
INSERT INTO stop_words(id, value) VALUES (9, 'вместе');
INSERT INTO stop_words(id, value) VALUES (10, 'около');
INSERT INTO stop_words(id, value) VALUES (11, 'он');
INSERT INTO stop_words(id, value) VALUES (12, 'оно');
INSERT INTO stop_words(id, value) VALUES (13, 'она');
INSERT INTO stop_words(id, value) VALUES (14, 'они');
INSERT INTO stop_words(id, value) VALUES (15, 'то');
INSERT INTO stop_words(id, value) VALUES (16, 'что');
INSERT INTO stop_words(id, value) VALUES (17, '');
