USE taskforce;
INSERT INTO users_specialisations(id, users_id, categories_id) VALUES (1, '1', '2');
INSERT INTO users_specialisations(id, users_id, categories_id) VALUES (2, '2', '5');
INSERT INTO users_specialisations(id, users_id, categories_id) VALUES (3, '5', '3');
INSERT INTO users_specialisations(id, users_id, categories_id) VALUES (4, '2', '6');
INSERT INTO users_specialisations(id, users_id, categories_id) VALUES (5, '8', '4');
INSERT INTO users_specialisations(id, users_id, categories_id) VALUES (6, '6', '5');
INSERT INTO users_specialisations(id, users_id, categories_id) VALUES (7, '7', '4');
INSERT INTO users_specialisations(id, users_id, categories_id) VALUES (8, '5', '4');
INSERT INTO users_specialisations(id, users_id, categories_id) VALUES (9, '3', '2');
INSERT INTO users_specialisations(id, users_id, categories_id) VALUES (10, '6', '1');
