USE taskforce;
INSERT INTO users_specialisations (id, user_id, cat_id) VALUES (1, '7', '5' );
INSERT INTO users_specialisations (id, user_id, cat_id) VALUES (2, '6', '7' );
INSERT INTO users_specialisations (id, user_id, cat_id) VALUES (3, '8', '2' );
INSERT INTO users_specialisations (id, user_id, cat_id) VALUES (4, '5', '5' );
INSERT INTO users_specialisations (id, user_id, cat_id) VALUES (5, '3', '8' );
INSERT INTO users_specialisations (id, user_id, cat_id) VALUES (6, '3', '3' );
INSERT INTO users_specialisations (id, user_id, cat_id) VALUES (7, '15', '7' );
INSERT INTO users_specialisations (id, user_id, cat_id) VALUES (8, '13', '8' );
INSERT INTO users_specialisations (id, user_id, cat_id) VALUES (9, '9', '1' );
INSERT INTO users_specialisations (id, user_id, cat_id) VALUES (10, '7', '1' );
