USE taskforce;
INSERT INTO stop_words SET id = 1,  value = и ;
INSERT INTO stop_words SET id = 2,  value = или ;
INSERT INTO stop_words SET id = 3,  value = в ;
INSERT INTO stop_words SET id = 4,  value = на ;
INSERT INTO stop_words SET id = 5,  value = у ;
INSERT INTO stop_words SET id = 6,  value = при ;
INSERT INTO stop_words SET id = 7,  value = с ;
INSERT INTO stop_words SET id = 8,  value = над ;
INSERT INTO stop_words SET id = 9,  value = вместе ;
INSERT INTO stop_words SET id = 10,  value = около ;
INSERT INTO stop_words SET id = 11,  value = он ;
INSERT INTO stop_words SET id = 12,  value = оно ;
INSERT INTO stop_words SET id = 13,  value = она ;
INSERT INTO stop_words SET id = 14,  value = они ;
INSERT INTO stop_words SET id = 15,  value = то ;
INSERT INTO stop_words SET id = 16,  value = что ;
