USE taskforce;
INSERT INTO users_specialisations SET id = 1,  user_id = 4,  cat_id = 6 ;
INSERT INTO users_specialisations SET id = 2,  user_id = 9,  cat_id = 6 ;
INSERT INTO users_specialisations SET id = 3,  user_id = 5,  cat_id = 6 ;
INSERT INTO users_specialisations SET id = 4,  user_id = 6,  cat_id = 1 ;
INSERT INTO users_specialisations SET id = 5,  user_id = 9,  cat_id = 8 ;
INSERT INTO users_specialisations SET id = 6,  user_id = 7,  cat_id = 8 ;
INSERT INTO users_specialisations SET id = 7,  user_id = 7,  cat_id = 8 ;
INSERT INTO users_specialisations SET id = 8,  user_id = 10,  cat_id = 8 ;
INSERT INTO users_specialisations SET id = 9,  user_id = 15,  cat_id = 7 ;
INSERT INTO users_specialisations SET id = 10,  user_id = 1,  cat_id = 1 ;
